### ISSUE TITLE
Some ecsact runtime functions need a delegate signature update

### ISSUE THREAD

**Issue by zaucy** [seaube/ecsact-unity#32]
Example: https://github.com/ecsact-dev/ecsact_runtime/blob/3ecc7d27a064b1d2899db33a859f34e836dcd1a0/ecsact/runtime/core.h#L115-L120

These functions now return an error code. I think we should throw a C# exception if these errors occur. These errors shouldn't be ignored by the user.
 - `ecsact_add_component`
 - `ecsact_update_component`
 - `ecsact_execute_systems`

**Comment by Kelwan** [comment]
Closed in a previous PR
