### ISSUE TITLE
Update to latest methods from the ecsact_runtime API and move Runtime `Core` functions to `ExecutionOptions`

### ISSUE THREAD

**Issue by Kelwan** [seaube/ecsact-unity#49]
With the removal and the `add`, `remove`, and `update` methods in the runtime, ecsact_unity should be updated as well.

- [x] Move Runtime `Core` functionality to `ExecutionOptions`. It should no longer be in `EcsactRuntime`
- [ ] Remove old methods (`add`, `remove`, `update`)

**Comment by zaucy** [comment]
partially done. We decided not to remove the old methods because they are still useful for tooling.
